/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/IMl7zG8fC2A
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
"use client"
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Badge } from "@/components/ui/badge"
import { Sheet, SheetTrigger, SheetContent } from "@/components/ui/sheet"
import { Switch } from "@/components/ui/switch"
import { Card, CardHeader, CardContent, CardFooter } from "@/components/ui/card"
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select"
import { Input } from "@/components/ui/input"

export function MultiChat() {
  return (
    <div className="flex h-screen">
      {/* <aside className="flex flex-col w-64 p-4 space-y-4 bg-background border-r md:flex">
        <div className="flex items-center space-x-2">
          <RocketIcon className="w-8 h-8" />
          <span className="text-2xl font-bold">
            Rocket<span className="text-primary">Chat</span>
          </span>
        </div>
        <nav className="flex flex-col space-y-2">
          <h2 className="text-sm font-semibold text-muted-foreground">AI Tools</h2>
          <Link
            href="#"
            className="flex items-center p-2 space-x-2 text-primary-foreground bg-primary rounded"
            prefetch={false}
          >
            <WebcamIcon className="w-5 h-5" />
            <span>AI Playground</span>
          </Link>
          <Link
            href="#"
            className="flex items-center p-2 space-x-2 text-muted-foreground hover:bg-muted/50 rounded"
            prefetch={false}
          >
            <LibraryIcon className="w-5 h-5" />
            <span>AI Library</span>
          </Link>
          <Link
            href="#"
            className="flex items-center p-2 space-x-2 text-muted-foreground hover:bg-muted/50 rounded"
            prefetch={false}
          >
            <FileTextIcon className="w-5 h-5" />
            <span>Chat PDF</span>
          </Link>
          <Link
            href="#"
            className="flex items-center p-2 space-x-2 text-muted-foreground hover:bg-muted/50 rounded"
            prefetch={false}
          >
            <ImageIcon className="w-5 h-5" />
            <span>Image Generator</span>
          </Link>
          <Link
            href="#"
            className="flex items-center p-2 space-x-2 text-muted-foreground hover:bg-muted/50 rounded"
            prefetch={false}
          >
            <Music2Icon className="w-5 h-5" />
            <span>Music Generator</span>
          </Link>
          <Link
            href="#"
            className="flex items-center p-2 space-x-2 text-muted-foreground hover:bg-muted/50 rounded"
            prefetch={false}
          >
            <CalendarIcon className="w-5 h-5" />
            <span>null</span>
          </Link>
        </nav>
        <div className="flex flex-col space-y-2">
          <h2 className="text-sm font-semibold text-muted-foreground">AI Models</h2>
          <div className="flex flex-wrap gap-2">
            <DoorOpenIcon className="w-8 h-8" />
            <EarthIcon className="w-8 h-8" />
            <TagsIcon className="w-8 h-8" />
            <StickerIcon className="w-8 h-8" />
          </div>
        </div>
        <div className="flex flex-col items-center p-4 mt-auto bg-muted rounded">
          <Button variant="outline">Upgrade to Pro</Button>
          <div className="flex items-center mt-2 space-x-2">
            <Avatar>
              <AvatarImage src="/placeholder-user.jpg" alt="User" />
              <AvatarFallback>A2</AvatarFallback>
            </Avatar>
            <div className="text-center">
              <Badge variant="secondary">FREE</Badge>
              <p className="text-sm font-semibold">ADARSH M 20B519</p>
            </div>
          </div>
        </div>
      </aside> */}
      <Sheet>
        <SheetTrigger asChild>
          <Button variant="outline" size="icon" className="md:hidden">
            <MenuIcon className="w-6 h-6" />
            <span className="sr-only">Toggle sidebar</span>
          </Button>
        </SheetTrigger>
        <SheetContent side="left" className="md:hidden">
          <div className="flex flex-col w-64 p-4 space-y-4 bg-background border-r">
            <div className="flex items-center space-x-2">
              <RocketIcon className="w-8 h-8" />
              <span className="text-2xl font-bold">
                Rocket<span className="text-primary">Chat</span>
              </span>
            </div>
            <nav className="flex flex-col space-y-2">
              <h2 className="text-sm font-semibold text-muted-foreground">AI Tools</h2>
              <Link
                href="#"
                className="flex items-center p-2 space-x-2 text-primary-foreground bg-primary rounded"
                prefetch={false}
              >
                <WebcamIcon className="w-5 h-5" />
                <span>AI Playground</span>
              </Link>
              <Link
                href="#"
                className="flex items-center p-2 space-x-2 text-muted-foreground hover:bg-muted/50 rounded"
                prefetch={false}
              >
                <LibraryIcon className="w-5 h-5" />
                <span>AI Library</span>
              </Link>
              <Link
                href="#"
                className="flex items-center p-2 space-x-2 text-muted-foreground hover:bg-muted/50 rounded"
                prefetch={false}
              >
                <FileTextIcon className="w-5 h-5" />
                <span>Chat PDF</span>
              </Link>
              <Link
                href="#"
                className="flex items-center p-2 space-x-2 text-muted-foreground hover:bg-muted/50 rounded"
                prefetch={false}
              >
                <ImageIcon className="w-5 h-5" />
                <span>Image Generator</span>
              </Link>
              <Link
                href="#"
                className="flex items-center p-2 space-x-2 text-muted-foreground hover:bg-muted/50 rounded"
                prefetch={false}
              >
                <Music2Icon className="w-5 h-5" />
                <span>Music Generator</span>
              </Link>
              <Link
                href="#"
                className="flex items-center p-2 space-x-2 text-muted-foreground hover:bg-muted/50 rounded"
                prefetch={false}
              >
                <CalendarIcon className="w-5 h-5" />
                <span>History</span>
              </Link>
            </nav>
            <div className="flex flex-col space-y-2">
              <h2 className="text-sm font-semibold text-muted-foreground">AI Models</h2>
              <div className="flex flex-wrap gap-2">
                <DoorOpenIcon className="w-8 h-8" />
                <EarthIcon className="w-8 h-8" />
                <TagsIcon className="w-8 h-8" />
                <StickerIcon className="w-8 h-8" />
              </div>
            </div>
            <div className="flex flex-col items-center p-4 mt-auto bg-muted rounded">
              <Button variant="outline">Upgrade to Pro</Button>
              <div className="flex items-center mt-2 space-x-2">
                <Avatar>
                  <AvatarImage src="/placeholder-user.jpg" alt="User" />
                  <AvatarFallback>A2</AvatarFallback>
                </Avatar>
                <div className="text-center">
                  <Badge variant="secondary">FREE</Badge>
                  <p className="text-sm font-semibold">ADARSH M 20B519</p>
                </div>
              </div>
            </div>
          </div>
        </SheetContent>
      </Sheet>
      <main className="flex-1 p-4 space-y-4 bg-background">
        <header className="flex items-center justify-between">
          <h1 className="text-2xl font-bold">Rocket sChat</h1>
          <div className="flex items-center space-x-4">
            <CalendarIcon className="w-6 h-6" />
            <LayoutGridIcon className="w-6 h-6" />
            <SettingsIcon className="w-6 h-6" />
            <div className="flex items-center space-x-2">
              <span>Sync Chats</span>
              <Switch className="flex items-center space-x-2">
                <span>Sync Chats</span>
                <Switch defaultChecked />
              </Switch>
            </div>
          </div>
        </header>
        <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
          <Card className="flex flex-col h-64">
            <CardHeader className="flex items-center justify-between">
              <Select>
                <SelectTrigger>
                  <SelectValue placeholder="Rocket AI" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="Rocket AI">Rocket AI</SelectItem>
                  <SelectItem value="Rocket AI Mini">Rocket AI Mini</SelectItem>
                  <SelectItem value="Rocket 3 Opus">Rocket 3 Opus</SelectItem>
                  <SelectItem value="Rocket 3.5 Sonnet">Rocket 3.5 Sonnet</SelectItem>
                </SelectContent>
              </Select>
            </CardHeader>
            <CardContent className="flex-1 overflow-auto" />
            <CardFooter className="flex items-center space-x-2">
              <Input placeholder="Type your message..." />
              <Button>Send</Button>
            </CardFooter>
          </Card>
          <Card className="flex flex-col h-64">
            <CardHeader className="flex items-center justify-between">
              <Select>
                <SelectTrigger>
                  <SelectValue placeholder="Rocket 3 Opus" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="Rocket AI">Rocket AI</SelectItem>
                  <SelectItem value="Rocket AI Mini">Rocket AI Mini</SelectItem>
                  <SelectItem value="Rocket 3 Opus">Rocket 3 Opus</SelectItem>
                  <SelectItem value="Rocket 3.5 Sonnet">Rocket 3.5 Sonnet</SelectItem>
                </SelectContent>
              </Select>
            </CardHeader>
            <CardContent className="flex-1 overflow-auto" />
            <CardFooter className="flex items-center space-x-2">
              <Input placeholder="Type your message..." />
              <Button>Send</Button>
            </CardFooter>
          </Card>
          <Card className="flex flex-col h-64">
            <CardHeader className="flex items-center justify-between">
              <Select>
                <SelectTrigger>
                  <SelectValue placeholder="Rocket 3.5 Sonnet" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="Rocket AI">Rocket AI</SelectItem>
                  <SelectItem value="Rocket AI Mini">Rocket AI Mini</SelectItem>
                  <SelectItem value="Rocket 3 Opus">Rocket 3 Opus</SelectItem>
                  <SelectItem value="Rocket 3.5 Sonnet">Rocket 3.5 Sonnet</SelectItem>
                </SelectContent>
              </Select>
            </CardHeader>
            <CardContent className="flex-1 overflow-auto" />
            <CardFooter className="flex items-center space-x-2">
              <Input placeholder="Type your message..." />
              <Button>Send</Button>
            </CardFooter>
          </Card>
        </div>
      </main>
    </div>
  )
}

function CalendarIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M8 2v4" />
      <path d="M16 2v4" />
      <rect width="18" height="18" x="3" y="4" rx="2" />
      <path d="M3 10h18" />
    </svg>
  )
}


function DoorOpenIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M13 4h3a2 2 0 0 1 2 2v14" />
      <path d="M2 20h3" />
      <path d="M13 20h9" />
      <path d="M10 12v.01" />
      <path d="M13 4.562v16.157a1 1 0 0 1-1.242.97L5 20V5.562a2 2 0 0 1 1.515-1.94l4-1A2 2 0 0 1 13 4.561Z" />
    </svg>
  )
}


function EarthIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M21.54 15H17a2 2 0 0 0-2 2v4.54" />
      <path d="M7 3.34V5a3 3 0 0 0 3 3v0a2 2 0 0 1 2 2v0c0 1.1.9 2 2 2v0a2 2 0 0 0 2-2v0c0-1.1.9-2 2-2h3.17" />
      <path d="M11 21.95V18a2 2 0 0 0-2-2v0a2 2 0 0 1-2-2v-1a2 2 0 0 0-2-2H2.05" />
      <circle cx="12" cy="12" r="10" />
    </svg>
  )
}


function FileTextIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7Z" />
      <path d="M14 2v4a2 2 0 0 0 2 2h4" />
      <path d="M10 9H8" />
      <path d="M16 13H8" />
      <path d="M16 17H8" />
    </svg>
  )
}


function ImageIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="18" height="18" x="3" y="3" rx="2" ry="2" />
      <circle cx="9" cy="9" r="2" />
      <path d="m21 15-3.086-3.086a2 2 0 0 0-2.828 0L6 21" />
    </svg>
  )
}


function LayoutGridIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="7" height="7" x="3" y="3" rx="1" />
      <rect width="7" height="7" x="14" y="3" rx="1" />
      <rect width="7" height="7" x="14" y="14" rx="1" />
      <rect width="7" height="7" x="3" y="14" rx="1" />
    </svg>
  )
}


function LibraryIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m16 6 4 14" />
      <path d="M12 6v14" />
      <path d="M8 8v12" />
      <path d="M4 4v16" />
    </svg>
  )
}


function MenuIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  )
}


function Music2Icon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="8" cy="18" r="4" />
      <path d="M12 18V2l7 4" />
    </svg>
  )
}


function RocketIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4.5 16.5c-1.5 1.26-2 5-2 5s3.74-.5 5-2c.71-.84.7-2.13-.09-2.91a2.18 2.18 0 0 0-2.91-.09z" />
      <path d="m12 15-3-3a22 22 0 0 1 2-3.95A12.88 12.88 0 0 1 22 2c0 2.72-.78 7.5-6 11a22.35 22.35 0 0 1-4 2z" />
      <path d="M9 12H4s.55-3.03 2-4c1.62-1.08 5 0 5 0" />
      <path d="M12 15v5s3.03-.55 4-2c1.08-1.62 0-5 0-5" />
    </svg>
  )
}


function SettingsIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z" />
      <circle cx="12" cy="12" r="3" />
    </svg>
  )
}


function StickerIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15.5 3H5a2 2 0 0 0-2 2v14c0 1.1.9 2 2 2h14a2 2 0 0 0 2-2V8.5L15.5 3Z" />
      <path d="M14 3v4a2 2 0 0 0 2 2h4" />
      <path d="M8 13h0" />
      <path d="M16 13h0" />
      <path d="M10 16s.8 1 2 1c1.3 0 2-1 2-1" />
    </svg>
  )
}


function TagsIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m15 5 6.3 6.3a2.4 2.4 0 0 1 0 3.4L17 19" />
      <path d="M9.586 5.586A2 2 0 0 0 8.172 5H3a1 1 0 0 0-1 1v5.172a2 2 0 0 0 .586 1.414L8.29 18.29a2.426 2.426 0 0 0 3.42 0l3.58-3.58a2.426 2.426 0 0 0 0-3.42z" />
      <circle cx="6.5" cy="9.5" r=".5" fill="currentColor" />
    </svg>
  )
}


function WebcamIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="10" r="8" />
      <circle cx="12" cy="10" r="3" />
      <path d="M7 22h10" />
      <path d="M12 22v-4" />
    </svg>
  )
}
